# Generated by Django 6.1 on 2026-08-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], max_length=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bandeira_cartao', models.CharField(blank=True, choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('ELO', 'Elo')], max_length=30)),
                ('responsavel', models.CharField(max_length=100)),
                ('num_caixa', models.CharField(max_length=20)),
                ('obs', models.TextField(blank=True)),
                ('conferido', models.BooleanField(default=False)),
            ],
        ),
    ]
